export { default as Features } from "./Features/Features.tsx"
export { default as Footer } from "./Footer/Footer.tsx"
export { default as Header } from "./Header/Header.tsx"
export { default as Intro } from "./Intro/Intro.tsx"
export { default as New } from "./New/New.tsx"
export { default as Partners } from "./Partners/Partners.tsx"
export { default as Products } from "./Products/Products.tsx"
